"""Initial migration with Document, ExtractionRequest, and AuditLog models

Revision ID: a404b670e487
Revises: 
Create Date: 2025-07-30 18:49:33.647836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a404b670e487'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.Enum('PDF', 'WORD', 'IMAGE', 'HANDWRITTEN', 'OTHER', name='documenttype'), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('upload_timestamp', sa.DateTime(), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('extraction_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('natural_language_request', sa.Text(), nullable=False),
    sa.Column('output_format', sa.Enum('JSON', 'CSV', 'XML', name='outputformat'), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'FLAGGED', name='extractionstatus'), nullable=True),
    sa.Column('created_timestamp', sa.DateTime(), nullable=True),
    sa.Column('started_timestamp', sa.DateTime(), nullable=True),
    sa.Column('completed_timestamp', sa.DateTime(), nullable=True),
    sa.Column('processing_time_seconds', sa.Float(), nullable=True),
    sa.Column('extracted_data', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('flagged_fields', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('identified_clauses', sa.Text(), nullable=True),
    sa.Column('risk_flags', sa.Text(), nullable=True),
    sa.Column('document_summary', sa.Text(), nullable=True),
    sa.Column('reference_materials', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('action', sa.Enum('DOCUMENT_UPLOAD', 'EXTRACTION_REQUEST', 'EXTRACTION_COMPLETED', 'EXTRACTION_FAILED', 'USER_FEEDBACK', 'DATA_EXPORT', 'MANUAL_CORRECTION', name='auditaction'), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('extraction_request_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['extraction_request_id'], ['extraction_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audit_logs')
    op.drop_table('extraction_requests')
    op.drop_table('documents')
    # ### end Alembic commands ###
